name: Tag Workflow

on:
  push:
    tags:
      - v*
permissions:
  contents: read
  id-token: write

jobs:
  tag:
    name: Tag Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Tag Workflow
        run: |
          echo "Tag Workflow"
          env
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check this tag commit at which branch
        run: |
          # check this tag commit at which branch
          git branch -r --contains ${{ github.ref_name }}
          # get the branch name
          BRANCH_NAME=$(git branch -r --contains ${{ github.ref_name }} | awk -F/ '{print $2}')
          echo "Branch Name: $BRANCH_NAME"